### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by Zachary-Rude** [RobinBoers/Platformed#1]
Hi,

I have noticed that, in the game, all of the text is in Dutch, which I do not understand. You should make your website multilingual by adding this JavaScript code to your game:

```js
document.getElementsByTagName("html")[0].lang = navigator.language;
```

**Comment by RobinBoers** [comment]
I coded it in Dutch. Does this make the browser translate it or something?

Edit: besides, this is a stupid and barely working project anyways. If you want an actually good game, check out [RobinBoers/cutie-tanks](https://github.com/RobinBoers/cutie-tanks) instead (or just open Steam).
